print('== Cadastro da Escola ==')
nome = input('Digite o nome: ')
print('Bem vindo(a) '+nome)
lazer = input('O que gosta de fazer? ')
print(lazer)
cor = input('Qual a sua cor preferida? ')
print('A cor preferida é '+cor)
time = input('Qual o seu time de futebol? ')
print('Time do Coração '+time)
filme = input('Qual o seu filme preferido! ')
print(filme)